Adding description introduction, changing extension name to (possibly) avoid invalid manifest.json problem
git-svn-id: http://dev.geogebra.org/svn/trunk/geogebra@17383 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/app/chrome/pack b/app/chrome/pack
--- a/app/chrome/pack
+++ b/app/chrome/pack
@@ -4,32 +4,43 @@
 # @author Zoltan Kovacs <zoltan@geogebra.org>
 
 # 1. Settings
-APPNAME=geogebra_chromeapp
+APPNAME=geogebra
 KEYFILE=igi-keystore-CL.key.pem
 AUTOBUILDCONF=../../desktop/scripts/autobuild/autobuild.conf
+VERSIONFILE=../../desktop/build/unpacked/version.txt
 
 test -r $AUTOBUILDCONF || {
  echo "No autobuild.conf exists in $AUTOBUILDCONF"
  exit 11
  }
 
+# FIXME, this is unelegant and slow
+test -r $VERSIONFILE || {
+ echo "$VERSIONFILE is missing - do a desktop build first"
+ exit 12
+ }
+
 . ../../desktop/scripts/autobuild/autobuild.conf
 
 test -r $P12DIR/$KEYFILE || {
  echo "No $KEYFILE exists in directory $P12DIR"
- exit 12
+ exit 13
  }
 
 # 2. Working directories
 MYDIR=`dirname $0`
 CHROMEDIR=`cd $MYDIR; pwd`
 WEBDIR=`cd $CHROMEDIR/../../web; pwd`
+VERSION=`cat $VERSIONFILE`
+
 
 cd $WEBDIR
 ./build -u safari -c -nl # -c: cleanup first, -nl: no languages (later should be removed)
 cp -r $WEBDIR/war/web $CHROMEDIR/$APPNAME
 cp $WEBDIR/war/app.html $CHROMEDIR/$APPNAME
 cd $CHROMEDIR
+cat $APPNAME/manifest.json.template | sed s/VERSION/$VERSION/g > \
+ $APPNAME/manifest.json
 
 # 3. Packaging
 rm -f $APPNAME.zip
