Adding ecj error support
git-svn-id: http://www.geogebra.org/svn/trunk/geogebra@14482 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/desktop/scripts/autobuild/build-pack-installer b/desktop/scripts/autobuild/build-pack-installer
--- a/desktop/scripts/autobuild/build-pack-installer
+++ b/desktop/scripts/autobuild/build-pack-installer
@@ -25,6 +25,7 @@ PURGE=1
 DELSRC=1
 LOGFILE=/tmp/build-pack-installer.log
 CV=4.2
+STOPONECJERR=1
 
 # 3. Reading command line arguments
 while [ $# -gt 0 ]; do
@@ -40,6 +41,7 @@ while [ $# -gt 0 ]; do
    echo "  -nd, --no-delete-src      Do not delete sources before SVN update"
    echo "  -ng, --no-grammar         Do not compile grammar with javacc"
    echo "  -nc, --no-classes         Do not (re)compile classes"
+   echo "  -ne, --no-ecj-err         Do not stop on an ecj error"
    echo "  -r [revision]             Use revision instead of latest"
    echo "  -l [logfile]              Use logfile instead of /tmp/build-pack-installer.log"
    echo "  -v, --verbose             Be verbose whenever possible"
@@ -65,6 +67,10 @@ while [ $# -gt 0 ]; do
    
   -nc | --no-classes)
    CLASSES=0
+   ;;
+
+  -ne | --no-ecj-err)
+   STOPONECJERR=0
    ;;
 
   -r)
@@ -163,7 +169,7 @@ if [ $DELSRC = 1 ]; then
  runstep 51 .delete-sources "Deleting sources" ant -f pack.xml delete-sources # FIXME: delete-sources must work for common as well
  fi
 
-runstep 2 .svn-update "SVN update" $SVN_COMMAND $REVISION_PARAM update --accept theirs-full --force ..
+runstep 2 .svn-update "SVN update" $SVN_COMMAND $REVISION_PARAM update --accept theirs-full --force .. org
 $SVN_COMMAND info | grep Revision | awk '{print $2}' > scripts/autobuild/.revision
 
 # 5/2. Downloading newest 3rd party libraries and installer tools
@@ -174,10 +180,15 @@ runstep 52 .installer "Downloading installer tools" ant
 # 6. Invoking make-vanilla-jars
 cd $WORKDIR/scripts/autobuild
 runstep 6 .build "Building" ./make-vanilla-jars -c
+cd $WORKDIR
+ECJRESULT=`tail -1 .ecjlog`
+log "Eclipse Compiler for Java found $ECJRESULT"
 appendlog .ecjlog
+if [ $STOPONECJERR = 1 ]; then
+ echo "$ECJRESULT" | grep --silent error && exit 6
+ fi
 
 # 7. Doing the rest (packing)
-cd $WORKDIR
 runstep 7 .pack "Packing" ant -f pack.xml $PROJECT-aftervanilla
 
 # 8. Creating Windows and Mac OS X installer
