Attempt to mirror the JAR files via rsync as well
git-svn-id: http://www.geogebra.org/svn/trunk/geogebra@13627 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/desktop/scripts/autobuild/push-to-mirrors b/desktop/scripts/autobuild/push-to-mirrors
--- a/desktop/scripts/autobuild/push-to-mirrors
+++ b/desktop/scripts/autobuild/push-to-mirrors
@@ -26,6 +26,11 @@ MYDIR=4.2
 cd $WWWDIR/$MYDIR
 MYVER=`cat unpacked/version.txt`
 
+if [ -r mirrors.conf ]; then
+ echo "mirrors.conf is missing, exiting"
+ exit 2
+ fi
+
 cat $SVNDIR/geogebra/desktop/scripts/autobuild/mirrors.conf | grep -v "^#" | grep -v "^$" | while read IP PORT RUSER DIR; do
  echo "Copying files to $RUSER@$IP:$PORT/$DIR..."
  # (Re)creating directories (-n is important to prevent reading data from cat):
