Theorem Proving: Some fixes for the Jenkins based benchmark
git-svn-id: http://dev.geogebra.org/svn/trunk/geogebra@42987 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/test/scripts/benchmark/prover/runtests b/test/scripts/benchmark/prover/runtests
--- a/test/scripts/benchmark/prover/runtests
+++ b/test/scripts/benchmark/prover/runtests
@@ -307,6 +307,10 @@ for i in `find -name '*.ggb' | sort`; do
 
   # Testing:
   if [ "$ENGINE" = "Web" ]; then
+   which $PHANTOMJS >/dev/null || {
+    echo "FATAL: PhantomJS is not found in $PHANTOMJS (>= 2.0.0 needed)"
+    exit 1
+    }
    test -d $ABSWEBDIR || {
     echo; echo "FATAL: folder $ABSWEBDIR does not exist. You have to compile web platform first."
     exit 1
