Firing sending warnings for junit test failures
git-svn-id: http://dev.geogebra.org/svn/trunk/geogebra@16294 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/test/scripts/autotest/junit-tests b/test/scripts/autotest/junit-tests
--- a/test/scripts/autotest/junit-tests
+++ b/test/scripts/autotest/junit-tests
@@ -16,11 +16,16 @@ cd $TESTDIR
 sleep 3 # Dirty hack to ensure xvfb can run properly
 xvfb-run -w 3 ./run-junit-tests || exit 1 # Problem running the tests
 ./junit2sqlite # Copying XML data into an SQL database
+./warnings > .warnings
 
 ERRORS=`cat .junit-tests-errors`
-
 if [ $ERRORS -gt 0 ]; then
  exit 2 # Errors occured during the JUnit tests
+ fi
+
+FAILURES=`cat .warnings`
+if [ "$FAILURES" != "" ]; then
+ exit 3 # A new failure has been introduced
  fi
 
 exit 0 # No error
