Attempt to detect Java 5 incompatible code
git-svn-id: http://www.geogebra.org/svn/trunk/geogebra@14151 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/test/scripts/autotest/simpletest b/test/scripts/autotest/simpletest
--- a/test/scripts/autotest/simpletest
+++ b/test/scripts/autotest/simpletest
@@ -16,10 +16,16 @@ cd $REVDIR/$REVISION || exit 1 # Build problem
 
 test -r geogebra.jar || exit 2 # Non-existing JAR
 
+
 xvfb-run timeout -k $SIMPLETESTTIMEOUT $SIMPLETESTTIMEOUT \
  $JAVA_HOME/bin/java -jar geogebra.jar --regressionFile=simpletest.out $MYDIR/simpletest.ggb \
   >simpletest.stdout 2>simpletest.stderr
 
 diff simpletest.out $MYDIR/simpletest.out || exit 3 # Problem with simple testing
+
+ECJERROR=`cat ecjerror`
+if [ "$ECJERROR" != "" ]; then
+ exit 4 # Compilation error (but GeoGebra started)
+ fi
 
 exit 0 # No error
