Attempt to fix alarm on web build errors
git-svn-id: http://dev.geogebra.org/svn/trunk/geogebra@15776 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/test/scripts/autotest/simpletest b/test/scripts/autotest/simpletest
--- a/test/scripts/autotest/simpletest
+++ b/test/scripts/autotest/simpletest
@@ -29,6 +29,9 @@ if [ "$ECJERROR" != "" ]; then
  exit 4 # Compilation error (but GeoGebra started)
  fi
 
-cat $WEBDIR/.buildlog | grep --silent "BUILD FAILED" && exit 5 # Problem with GeoGebraWeb
+WEBERROR=`cat weberrors`
+if [ "$WEBERROR" != "" ]; then
+ exit 5 # Compilation error (but GeoGebra started)
+ fi
 
 exit 0 # No error
