Exit codes are preserved
git-svn-id: http://www.geogebra.org/svn/trunk/geogebra@15306 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/web/build b/web/build
--- a/web/build
+++ b/web/build
@@ -2,19 +2,22 @@
 # Compiles GeoGebraWeb via command line.
 # @author Zoltan Kovacs <zoltan@geogebra.org>
 # Make sure that you run this script from its directory.
-# 1. Setting up environment variables
-#Functions first
-#Cleanup: Removing links not to break eclipse
+
+# 0. Functions first
+
+# Cleanup: Removing links not to break Eclipse
 cleanup() {
-    echo "Cleaning up..."
-    ${WEBDIR_LINK_TARGET?" is not set: nothing to clean up"}
-        cd $WEBDIR_LINK_TARGET
-        for i in *; do
-                if test -L $i; then
-                    rm -rf $i;
-                    echo "cleanup: removing link: $i"
-                fi
-            done
+ LASTEXITCODE=$?
+ if [ "$WEBDIR_LINK_TARGET" != "" ]; then
+  cd $WEBDIR_LINK_TARGET
+  for i in *; do
+   test -L $i && {
+    rm $i
+    echo "Cleaning up: removing link: $i"
+    }
+   done
+  fi
+ exit $LASTEXITCODE
 }
 
 speccomp() {
@@ -29,6 +32,8 @@ cat $PROJECT.gwt.xml-var | sed s/"\${useragents}"/"$USERAGENTS"/g \
 
 trap "cleanup" EXIT 2 9 15
 
+# 1. Setting up environment variables
+
 GWTDIR=../gwt-2.4.0 # Override it if needed by using autobuild.conf
 test -r autobuild.conf && . ./autobuild.conf && echo "$0: Using autobuild.conf for overriding defaults"
 
@@ -39,7 +44,7 @@ if [ "$SVNDIR" = "" ]; then
 else
  WORKDIR=`cd $SVNDIR/geogebra/web; pwd`
  fi
-echo "using $GWTDIR for get GWT jars\n"
+
 export GWTDIR
 cd $WORKDIR
 WEBDIR=`pwd`
@@ -120,6 +125,8 @@ else
 
 MYARGS="<arg line=\\\"-style $STYLE\\\"\/>"
 
+echo "GWT SDK directory is set to $GWTDIR"
+
 # 2. (Re)creating parser
 echo "$0: (Re)creating parser"
 cd ../desktop
@@ -163,6 +170,4 @@ else
  echo "file:///$INSTALLDIR/Web.html"
  fi
 
-
-exit 0;
-
+exit 0
