Fixing command line build (and syncing with Eclipse)
git-svn-id: http://www.geogebra.org/svn/trunk/geogebra@15404 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/web/build b/web/build
--- a/web/build
+++ b/web/build
@@ -5,43 +5,74 @@
 
 # 0. Functions first
 
-# Cleanup: Removing links not to break Eclipse
+# Cleanup
 cleanup() {
  LASTEXITCODE=$?
- if [ "$WEBDIR_LINK_TARGET" != "" ]; then
-  cd $WEBDIR_LINK_TARGET
-  for i in *; do
-   test -L $i && {
-    rm $i
-    echo "Cleaning up: removing link: $i"
-    }
-   done
-  for PROJECT in Common Web; do
-   PLC=`echo $PROJECT | awk '{print tolower($1)}'`
-   echo "Cleaning up: putting back original $PROJECT.gwt.xml"
-   cd $WEBDIR/../$PLC/src/geogebra
-   mv $PROJECT.gwt.xml.orig $PROJECT.gwt.xml
-   done
-  fi
+ test -r $WEBDIR/src/geogebra/Web.gwt.xml.orig && {
+  echo "Cleaning up: putting back original Web.gwt.xml"
+  cd $WEBDIR/src/geogebra
+  mv Web.gwt.xml.orig Web.gwt.xml
+  }
  exit $LASTEXITCODE
 }
 
-speccomp() {
-echo "$0: Preparing specifing compilation settings for $1"
-PROJECT=$1
-PLC=`echo $PROJECT | awk '{print tolower($1)}'`
-cd $WEBDIR/../$PLC/src/geogebra
-cp $PROJECT.gwt.xml $PROJECT.gwt.xml.orig
-cat $PROJECT.gwt.xml-var | sed s/"\${useragents}"/"$USERAGENTS"/g \
- | sed s/"<!-- \$linker -->"/"$XS"/g > $PROJECT.gwt.xml
-}
+# Lists the newest file according to the $1 pattern
+l() {
+ ls -1 -t $1 | tail -1
+ }
 
-trap "cleanup" EXIT 2 9 15
+# Sets the classpath. This must be fine tuned
+# and maybe tidied up a bit, FIXME
+classpath() {
+CLASSPATH=\
+$GGDIR/web/src:\
+$GGDIR/common/src:\
+$GGDIR/common/war/WEB-INF/lib:\
+$GGDIR/common/src/geogebra/jre:\
+$GGDIR/common/src/geogebra/webapache:\
+/web/test-classes:\
+$GGDIR/web/war/WEB-INF/classes:\
+$GWTDIR/gwt-user.jar:\
+$GWTDIR/gwt-dev.jar:\
+`l $GWTDIR/validation-api-*.GA-sources.jar`:\
+`l $GWTDIR/validation-api-*.GA.jar`:\
+$GGDIR/common/test-classes:\
+$GGDIR/common/war/WEB-INF/classes:\
+`l $GAEDIR/lib/shared/jsp/repackaged-appengine-ant-*.jar`:\
+`l $GAEDIR/lib/shared/jsp/repackaged-appengine-ant-launcher-*.jar`:\
+`l $GAEDIR/lib/shared/jsp/repackaged-appengine-jasper-*.jar`:\
+`l $GAEDIR/lib/shared/jsp/repackaged-appengine-jasper-el-*.jar`:\
+`l $GAEDIR/lib/shared/jsp/repackaged-appengine-tomcat-juli-*.jar`:\
+$GAEDIR/lib/shared/appengine-local-runtime-shared.jar:\
+$GAEDIR/lib/shared/el-api.jar:\
+$GAEDIR/lib/shared/jsp-api.jar:\
+$GAEDIR/lib/shared/servlet-api.jar:\
+`l $GAEDIR/lib/user/orm/datanucleus-appengine-*.final.jar`:\
+`l $GAEDIR/lib/user/orm/datanucleus-core-*.jar`:\
+`l $GAEDIR/lib/user/orm/datanucleus-jpa-*.jar`:\
+`l $GAEDIR/lib/user/orm/geronimo-jpa_*_spec-*.jar`:\
+`l $GAEDIR/lib/user/orm/geronimo-jta_*_spec-*.jar`:\
+`l $GAEDIR/lib/user/orm/jdo2-api-*-eb.jar`:\
+`l $GAEDIR/lib/user/appengine-api-*-sdk-*.jar`:\
+`l $GAEDIR/lib/user/appengine-api-labs-*.jar`:\
+`l $GAEDIR/lib/user/appengine-jsr*cache-*.jar`:\
+`l $GAEDIR/lib/user/jsr*cache-*.jar`:\
+$GAEDIR/lib/appengine-tools-api.jar:\
+$GWTDIR/gwt-dev.jar
+
+export CLASSPATH
+}
 
 # 1. Setting up environment variables
 
 GWTDIR=../gwt-2.4.0 # Override it if needed by using autobuild.conf
-test -r autobuild.conf && . ./autobuild.conf && echo "$0: Using autobuild.conf for overriding defaults"
+XML=`which xml 2>/dev/null`
+if [ "$XML" = "" ]; then
+ XML=`pwd`/xml
+ fi
+GGDIR=`cd ..; pwd`
+
+test -r autobuild.conf && . ./autobuild.conf && echo "Using autobuild.conf for overriding defaults"
 
 # 2. Setting defaults
 if [ "$SVNDIR" = "" ]; then
@@ -58,8 +89,11 @@ WEBDIR=`pwd`
 VERBOSE=0
 USERAGENTS=gecko1_8,safari,ie9,opera
 INSTALLDIR=""
-XS=""
+XS=0
 STYLE=OBFUSCATED
+OTHEROPTS=""
+
+trap "cleanup" EXIT 2 9 15
 
 # 3. Reading command line arguments
 while [ $# -gt 0 ]; do
@@ -75,14 +109,19 @@ while [ $# -gt 0 ]; do
    echo "  -x                  XS compilation"
    echo "  -s [style]          Compilation style: OBFUSCATED, PRETTY or DETAILED ($STYLE)"
    echo "  -g [directory]      Use GWT SDK from the given directory ($GWTDIR)"
+   echo "  -gae [directory]    Use GAE SDK from the given directory ($GAEDIR)"
+   echo "  -X [path]           Use XMLStarlet from the given path ($XML)"
    echo "  -v, --verbose       Be verbose whenever possible"
+   echo "  -- [options]        Forward the rest options directly to the GWT Compiler"
+   echo "  -H                  Show extra options for the GWT Compiler"
+   echo
+   echo "Example: ./build -X /usr/local/bin/xml -s PRETTY -u safari -i /tmp/ggw -- -draftCompile"
    exit 0
    ;;
 
   -u)
    shift
    USERAGENTS="$1"
-   echo "Compiling for $1"
    ;;
 
   -i)
@@ -90,28 +129,46 @@ while [ $# -gt 0 ]; do
    INSTALLDIR="$1"
    ;;
 
+  -X)
+   shift
+   XML="$1"
+   ;;
+
   -x)
-   XS="<add-linker name=\\\"xs\\\"\/>"
-   echo "Compiling with XS (cross site)"
+   XS=1
    ;;
 
   -s)
    shift
    STYLE="$1"
-   echo "Compiling with $STYLE"
    ;;
    
   -g)
    shift
    GWTDIR="$1"
-   test -d $GWTDIR || {
-    echo "No GWT SDK directory exists at $GWTDIR"
-    exit 1
-    }
+   ;;
+
+  -gae)
+   shift
+   GAEDIR="$1"
    ;;
 
   -v | --verbose)
    VERBOSE=1
+   ;;
+   
+  --)
+   shift
+   OTHEROPTS=$*
+   while [ "$2" != "" ]; do
+    shift
+    done
+   ;;
+   
+  -H)
+   classpath
+   java com.google.gwt.dev.Compiler
+   exit 0
    ;;
 
   *)
@@ -129,45 +186,61 @@ else
  ANT="ant"
  fi
 
-MYARGS="<arg line=\\\"-style $STYLE\\\"\/>"
+# Testing configuration
+test -d $GWTDIR || {
+ echo "No GWT SDK directory exists at $GWTDIR"
+ exit 1
+}
+test -d $GAEDIR || {
+ echo "No GAE SDK directory exists at $GAEDIR"
+ exit 1
+ }
+test -x $XML || {
+ echo "No XMLStarlet executable exists at $XML"
+ exit 1
+ }
+
 
 echo "GWT SDK directory is set to $GWTDIR"
+echo "GAE SDK directory is set to $GAEDIR"
+echo "User agents: $USERAGENTS"
+echo "Compilation style: $STYLE"
+echo
 
 # 2. (Re)creating parser
-echo "$0: (Re)creating parser"
 cd ../desktop
 $ANT compile-grammar-cl || exit 2
 
-# 3. Creating symlinks to common
-echo "$0: Creating symlinks to common"
-cd ../common
-COMMONDIR=`pwd`
-COMMONDIR_LINK_SOURCE=$COMMONDIR/src/geogebra
-WEBDIR_LINK_TARGET=$WEBDIR/src/geogebra
-cd $COMMONDIR_LINK_SOURCE
-for i in *; do
- cd $WEBDIR_LINK_TARGET
- test -L $i || ln -s $COMMONDIR_LINK_SOURCE/$i
- done
+# 3. Preparing specific compilation
+cd ../web/src/geogebra
+GWTXML=Web.gwt.xml
+cp $GWTXML $GWTXML.orig
 
-# 4. Preparing specific compilation
+cat $GWTXML | \
+ $XML ed -u "/module/set-property[@name='user.agent']/@value" -v "$USERAGENTS" > $GWTXML-b
 
-speccomp Common
-speccomp Web
+if [ "$XS" = "1" ]; then
+ cat $GWTXML-b | \
+  $XML ed -d /module/add-linker |\
+  $XML ed -s /module -t elem -n "add-linker" -v "" |\
+  $XML ed -i /module/add-linker -t attr -n name -v xs > $GWTXML-b2
+ mv $GWTXML-b2 $GWTXML-b
+ fi
 
-# 5. Compiling web
-echo "$0: Compiling web"
-cd ../..
-cat build.xml | sed s/"<!-- \$myargs -->"/"$MYARGS"/g > mybuild.xml
-$ANT -f mybuild.xml clean build || exit 4
+mv $GWTXML-b $GWTXML
 
-# 6. Done!
+# 4. Compiling web
+classpath
+java -Xmx512m com.google.gwt.dev.Compiler\
+ -style $STYLE -war $GGDIR/web/war -strict $OTHEROPTS geogebra.Web || exit 4
+
+# 5. Done!
 if [ "$INSTALLDIR" = "" ]; then
  echo "GeoGebraWeb compilation finished. Insert this URL into your browser to test it:"
  echo "file:///$WEBDIR/war/Web.html"
 else
  echo "Trying to (re)create $INSTALLDIR..."
- mkdir -p $INSTALLDIR || exit 6
+ mkdir -p $INSTALLDIR || exit 5
  cp -a $WEBDIR/war/* $INSTALLDIR
  for i in .svn WEB-INF; do
   rm -fR $INSTALLDIR/$i
