Making possible to create different sort of web-builds for command line
git-svn-id: http://www.geogebra.org/svn/trunk/geogebra@15245 23ce0884-8a58-47d3-bc5c-ddf1cd5b9f9e

diff --git a/web/build b/web/build
--- a/web/build
+++ b/web/build
@@ -6,13 +6,74 @@
 
 # 1. Setting up environment variables
 GWTDIR=../gwt-2.4.0 # Override it if needed by using autobuild.conf
+test -r autobuild.conf || {
+ echo "$0: Cannot find autobuild.conf (make sure you edit autobuild.conf.dist first)"
+ echo "Continuing with defaults anyway..."
+ }
 test -r autobuild.conf && . ./autobuild.conf
+
+# 2. Setting defaults
+if [ "$SVNDIR" = "" ]; then
+ ORIGDIR=`dirname $0`
+ WORKDIR=`cd $ORIGDIR; pwd`
+else
+ WORKDIR=`cd $SVNDIR/geogebra/web; pwd`
+ fi
 export GWTDIR
+cd $WORKDIR
 WEBDIR=`pwd`
+
+VERBOSE=0
+USERAGENTS=gecko1_8,safari,ie9,opera
+INSTALLDIR=""
+
+# 3. Reading command line arguments
+while [ $# -gt 0 ]; do
+ case $1 in
+  -h | -help | --help)
+   echo "This script builds and installs GeoGebraWeb."
+   echo
+   echo "Usage: $0 [options]"
+   echo " Where options can be (defaults in parentheses):"
+   echo "  -h, -help, --help   This help"
+   echo "  -u [useragents]     Comma separated list of user agents to compile (default: $USERAGENTS)"
+   echo "  -i [directory]      If set, installs GeoGebraWeb into the given dir"
+   echo "  -v, --verbose       Be verbose whenever possible"
+   exit 0
+   ;;
+
+  -u)
+   shift
+   USERAGENTS="$1"
+   ;;
+
+  -i)
+   shift
+   INSTALLDIR="$1"
+   ;;
+
+  -v | --verbose)
+   VERBOSE=1
+   ;;
+
+  *)
+   echo "Unknown parameter: $1. Use \"$0 -h\" for help."
+   exit 1
+   ;;
+
+  esac
+ shift
+ done
+
+if [ "$VERBOSE" = 1 ]; then
+ ANT="ant -v"
+else
+ ANT="ant"
+ fi
 
 # 2. (Re)creating parser
 cd ../desktop
-ant compile-grammar-cl || exit 2
+$ANT compile-grammar-cl || exit 2
 
 # 3. Creating symlinks to common
 cd ../common
@@ -25,23 +86,33 @@ for i in *; do
  test -L $i || ln -s $COMMONDIR_LINK_SOURCE/$i
  done
 
-# 4. Preparing full compilation
-fullcomp() {
+# 4. Preparing specific compilation
+speccomp() {
 cd $WEBDIR
 PROJECT=$1
 PLC=`echo $PROJECT | awk '{print tolower($1)}'`
 cd ../$PLC/src/geogebra
-cp $PROJECT.gwt.xml-full $PROJECT.gwt.xml
+cat $PROJECT.gwt.xml-var | sed s/"\${useragents}"/"$USERAGENTS"/g > $PROJECT.gwt.xml
 }
 
-fullcomp Common
-fullcomp Web
+speccomp Common
+speccomp Web
 
 # 5. Compiling web
 cd ../..
-ant clean build || exit 4
+$ANT clean build || exit 4
 
 # 6. Done!
-echo "GeoGebraWeb compilation finished. Insert this URL into your browser to test it:"
-THISDIR=`pwd`
-echo "file:///$THISDIR/war/ggbtest.html"
+if [ "$INSTALLDIR" = "" ]; then
+ echo "GeoGebraWeb compilation finished. Insert this URL into your browser to test it:"
+ echo "file:///$WEBDIR/war/Web.html"
+else
+ echo "Trying to (re)create $INSTALLDIR..."
+ mkdir -p $INSTALLDIR || exit 6
+ cp -a $WEBDIR/war/* $INSTALLDIR
+ for i in .svn WEB-INF; do
+  rm -fR $INSTALLDIR/$i
+  done
+ echo "GeoGebraWeb compilation finished. Insert this URL into your browser to test it:"
+ echo "file:///$INSTALLDIR/Web.html"
+ fi
